name: Build & test on Windows

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 5" # At 00:00 every Friday

jobs:
  build_and_test_windows:
    runs-on: windows-2022
    env:
      # Disable progress bar in Cargo. This cuts down on output, avoiding log length limits.
      TERM: dumb

    strategy:
      fail-fast: false
      matrix:
        # TODO: Add a build that does NOT rely on the pre-compiled gettext.
        include:
          - rust-version: stable
            use_precompiled: true
            bits: "64"
            env:
              TARGET: x86_64-pc-windows-msvc
            name: "x86_64, Rust stable"
          - rust-version: stable
            use_precompiled: true
            bits: "32"
            env:
              TARGET: i686-pc-windows-gnu
            name: "i686, Rust stable"
          - rust-version: beta
            use_precompiled: true
            bits: "64"
            env:
              TARGET: x86_64-pc-windows-msvc
            name: "x86_64, Rust beta"
          - rust-version: nightly
            use_precompiled: true
            bits: "32"
            env:
              TARGET: i686-pc-windows-gnu
            name: "x86_64, Rust nightly"

    name: ci/run.sh on ${{ matrix.name }}

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust-version }}

        # setup-rust-action turns panic messages in tests into GitHub
        # annotations. Our test suite is running with --verbose, and prints out
        # messages even for panics that we do expect. setup-rust-action can't
        # know about this though, and floods the UI with annotations. This
        # command disables annotations for tests.
      - name: Disable GitHub Annotations
        run: echo '::remove-matcher owner=cargo-test::'

      - name: Add appropriate target to Cargo
        run: rustup target add ${{ matrix.env.TARGET }}
        if: ${{ ! matrix.env.NO_ADD }}

      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # required for successfully fetching gettext :(
          submodules: recursive

      ###
      - name: Download gettext archive
        if: ${{ matrix.use_precompiled }}
        uses: suisei-cn/actions-download-file@v1
        with:
          url: https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.21-v1.16/gettext0.21-iconv1.16-static-${{ matrix.bits }}.zip
          target: gettext/

      - name: Extract gettext
        if: ${{ matrix.use_precompiled }}
        run: 7z x gettext0.21-iconv1.16-static-${{ matrix.bits }}.zip
        working-directory: gettext/

      - name: Update GETTEXT_DIR
        if: ${{ matrix.use_precompiled }}
        run: echo ("GETTEXT_DIR=${{ github.workspace }}/gettext") >> $env:GITHUB_ENV
      ###

      - name: Generate lockfile
        run: cargo generate-lockfile

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          key: ${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
      - run: |
          chcp 65001 #set code page to utf-8
          echo ("TARGET=${{ matrix.env.TARGET }}") >> $env:GITHUB_ENV
      - name: ./ci/run.sh
        run: sh ci/run.sh
